# Generated by Django 4.0.4 on 2022-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PR', 'В процессе'), ('DN', 'Выполнена')], default='PR', max_length=2, verbose_name='Статус'),
        ),
    ]
